version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod
    container_name: my_sns_app_prod
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.prod

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: my_sns_nginx_prod
    ports:
      - "80:80"
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: my_sns_db_prod
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
